### ISSUE TITLE
Invalid git cherry-pick argument

### ISSUE THREAD

**Issue by GiyoMoon** [zegl/extremely-linear#1]
Hey! I just noticed that the argument `--allow-empty-messages` does not exist for `git cherry-pick` and the program will crash if it tries to execute this command. It should be `--allow-empty-message`.

https://github.com/zegl/extremely-linear/blob/00000300cc6862fc32cbcd1e774bf54dd64e4e70/git-linearize#L181

Love this funny tool btw! Great job :D

**Comment by zegl** [comment]
@GiyoMoon You're crazy for actually using this – I love it!

Thanks for letting me know, the bug has been fixed now. :-)
